package com.projectkorra.core.game;


public enum InputType {

	LEFT_CLICK, SHIFT_DOWN, SHIFT_UP, SPRINT_ON, SPRINT_OFF, LEFT_CLICK_BLOCK, RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, NONE, LEFT_CLICK_OFF_HAND, LEFT_CLICK_BLOCK_OFF_HAND, RIGHT_CLICK_AIR_OFF_HAND, RIGHT_CLICK_BLOCK_OFF_HAND;

}
